stages:
  - build
  - test
  - deploy

variables:
  BUILD_DIR: "build"

before_script:
  - mkdir -p $BUILD_DIR

build_job:
  stage: build
  script:
    - make all

test_job:
  stage: test
  script:
    - make test

deploy_job:
  stage: deploy
  script:
    - st-flash write firmware.bin 0x8000000
